/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit, regenerate with tools/ctlv/ctlv-regen.sh, from: */
/*	Documentation/ctlv/specs/ctlv.yaml */
/* CTLV-GEN uapi header */

/*
 * Constants of the ctlv CTLV family. Attr and op IDs are complete; the wire
 * format carrying them is in <linux/ctlv.h>.
 */

#ifndef _UAPI_LINUX_CTLV_GEN_H
#define _UAPI_LINUX_CTLV_GEN_H

#include <linux/ctlv.h>

#define CTLV_FAMILY_ID 0

/* enum op-type */
enum ctlv_op_type {
	CTLV_OP_TYPE_ACTION = 1,
	CTLV_OP_TYPE_QUERY = 2,
	CTLV_OP_TYPE_EVENT = 3,
};

/* enum op-availability */
enum ctlv_op_availability {
	CTLV_OP_AVAILABILITY_FIXED = 1,
	CTLV_OP_AVAILABILITY_DYNAMIC = 2,
};

/* enum blob-type */
enum ctlv_blob_type {
	CTLV_BLOB_TYPE_VA = 1,
	CTLV_BLOB_TYPE_MEMFD = 2,
	CTLV_BLOB_TYPE_DMA_BUF = 3,
};

/* enum blob-direction */
enum ctlv_blob_direction {
	CTLV_BLOB_DIRECTION_INPUT = 1,
	CTLV_BLOB_DIRECTION_OUTPUT = 2,
	CTLV_BLOB_DIRECTION_INOUT = 3,
};

/* enum validation-reason */
enum ctlv_validation_reason {
	CTLV_VALIDATION_REASON_MALFORMED_MESSAGE = 1,
	CTLV_VALIDATION_REASON_UNKNOWN_ATTR = 2,
	CTLV_VALIDATION_REASON_UNKNOWN_FLAG = 3,
	CTLV_VALIDATION_REASON_NESTING_TOO_DEEP = 4,
	CTLV_VALIDATION_REASON_MISSING_ATTR = 5,
	CTLV_VALIDATION_REASON_TOO_MANY_OCCURRENCES = 6,
	CTLV_VALIDATION_REASON_VALUE_OUT_OF_RANGE = 7,
	CTLV_VALIDATION_REASON_BAD_LENGTH = 8,
	CTLV_VALIDATION_REASON_BAD_STRING = 9,
	CTLV_VALIDATION_REASON_BAD_BLOB_DESCRIPTOR = 10,
	CTLV_VALIDATION_REASON_STALE_GENERATION = 11,
};

/* attr group family */
#define CTLV_GROUP_FAMILY 1

#define CTLV_ATTR_FAMILY_ID CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_FAMILY, 1)
#define CTLV_ATTR_FAMILY_NAME CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_FAMILY, 2)
#define CTLV_ATTR_FAMILY_ENTRY \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_FAMILY, 3)

/* attr group blob */
#define CTLV_GROUP_BLOB 2

#define CTLV_ATTR_BLOB_TYPE CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_BLOB, 1)
#define CTLV_ATTR_BLOB_ADDRESS CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_BLOB, 2)
#define CTLV_ATTR_BLOB_FD CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_BLOB, 3)
#define CTLV_ATTR_BLOB_OFFSET CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_BLOB, 4)
#define CTLV_ATTR_BLOB_LENGTH CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_BLOB, 5)

/* attr group error */
#define CTLV_GROUP_ERROR 3

#define CTLV_ATTR_ERROR_REASON CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_ERROR, 1)
#define CTLV_ATTR_ERROR_MESSAGE \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_ERROR, 2)
#define CTLV_ATTR_ERROR_BAD_ATTR_OFFSET \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_ERROR, 3)
#define CTLV_ATTR_ERROR_NEST_OFFSET \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_ERROR, 4)
#define CTLV_ATTR_ERROR_MISSING_ATTR_ID \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_ERROR, 5)
#define CTLV_ATTR_ERROR_EXPECTED_GENERATION \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_ERROR, 6)
#define CTLV_ATTR_ERROR_CURRENT_GENERATION \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_ERROR, 7)

/* attr group op */
#define CTLV_GROUP_OP 4

#define CTLV_ATTR_OP_ID CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_OP, 1)
#define CTLV_ATTR_OP_TYPE CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_OP, 2)
#define CTLV_ATTR_OP_AVAILABILITY CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_OP, 3)
#define CTLV_ATTR_OP_DISABLED CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_OP, 4)
#define CTLV_ATTR_OP_REQUEST_MAX_LEN \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_OP, 5)
#define CTLV_ATTR_OP_ACTION_REPLY_MAX_LEN \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_OP, 6)
#define CTLV_ATTR_OP_QUERY_REPLY_MIN_LEN \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_OP, 7)
#define CTLV_ATTR_OP_QUERY_REPLY_SUGGESTED_LEN \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_OP, 8)
#define CTLV_ATTR_OP_EVENT_RECORD_MAX_LEN \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_OP, 9)
#define CTLV_ATTR_OP_STATE_GENERATION \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_OP, 10)
#define CTLV_ATTR_OP_ENTRY CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_OP, 11)

/* attr group schema */
#define CTLV_GROUP_SCHEMA 5

#define CTLV_ATTR_SCHEMA_ATTR_ID \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 1)
#define CTLV_ATTR_SCHEMA_KIND CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 2)
#define CTLV_ATTR_SCHEMA_MAX_OCCURRENCES \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 3)
#define CTLV_ATTR_SCHEMA_MIN CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 4)
#define CTLV_ATTR_SCHEMA_MAX CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 5)
#define CTLV_ATTR_SCHEMA_MIN_LENGTH \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 6)
#define CTLV_ATTR_SCHEMA_MAX_LENGTH \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 7)
#define CTLV_ATTR_SCHEMA_FLAGS_MASK \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 8)
#define CTLV_ATTR_SCHEMA_UNIT CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 9)
#define CTLV_ATTR_SCHEMA_SCALE \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 10)
#define CTLV_ATTR_SCHEMA_BLOB_DIRECTION \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 11)
#define CTLV_ATTR_SCHEMA_BLOB_BACKINGS \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 12)
#define CTLV_ATTR_SCHEMA_BLOB_MAX_LENGTH \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 13)
#define CTLV_ATTR_SCHEMA_BLOB_ALIGNMENT \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 14)
#define CTLV_ATTR_SCHEMA_REENTERS \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 15)
#define CTLV_ATTR_SCHEMA_ATTRS \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 16)
#define CTLV_ATTR_SCHEMA_OPTIONAL_ATTRS \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 17)
#define CTLV_ATTR_SCHEMA_REQUEST \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 18)
#define CTLV_ATTR_SCHEMA_REPLY \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_SCHEMA, 19)

/* attr group event */
#define CTLV_GROUP_EVENT 6

#define CTLV_ATTR_EVENT_OP_ID CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_EVENT, 1)
#define CTLV_ATTR_EVENT_QUEUE_LEN \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_EVENT, 2)
#define CTLV_ATTR_EVENT_QUEUE_LEN_UNIT CTLV_UNIT_BYTES
#define CTLV_ATTR_EVENT_QUEUE_LEN_SCALE 0
#define CTLV_ATTR_EVENT_QUEUE_USED \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_EVENT, 3)
#define CTLV_ATTR_EVENT_QUEUE_USED_UNIT CTLV_UNIT_BYTES
#define CTLV_ATTR_EVENT_QUEUE_USED_SCALE 0
#define CTLV_ATTR_EVENT_FIRST_SEQUENCE \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_EVENT, 4)
#define CTLV_ATTR_EVENT_LAST_SEQUENCE \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_EVENT, 5)
#define CTLV_ATTR_EVENT_DROPPED_COUNT \
	CTLV_ATTR_ID(CTLV_FAMILY_ID, CTLV_GROUP_EVENT, 6)

/* attr sets */
#define CTLV_SET_FAMILY_ENTRY 1
#define CTLV_SET_OP_ENTRY 2
#define CTLV_SET_OP_SCHEMA_REQUEST 3
#define CTLV_SET_SCHEMA_NODE 4
#define CTLV_SET_OP_SCHEMA_INFO 5
#define CTLV_SET_OP_CHANGE_INFO 6
#define CTLV_SET_ERROR_INFO 7
#define CTLV_SET_EVENT_SUBSCRIPTION 8
#define CTLV_SET_EVENT_QUEUE_LIMIT 9
#define CTLV_SET_EVENT_QUEUE_STATE 10
#define CTLV_SET_EVENT_OVERFLOW_INFO 11

/* ops */
#define CTLV_OP_FAMILIES_DUMP CTLV_OP_ID(CTLV_FAMILY_ID, 1)
#define CTLV_OP_OPS_DUMP CTLV_OP_ID(CTLV_FAMILY_ID, 2)
#define CTLV_OP_OP_SCHEMA_GET CTLV_OP_ID(CTLV_FAMILY_ID, 3)
#define CTLV_OP_SUBSCRIPTIONS_ADD CTLV_OP_ID(CTLV_FAMILY_ID, 4)
#define CTLV_OP_SUBSCRIPTIONS_REMOVE CTLV_OP_ID(CTLV_FAMILY_ID, 5)
#define CTLV_OP_EVENT_QUEUE_GET CTLV_OP_ID(CTLV_FAMILY_ID, 6)
#define CTLV_OP_EVENT_QUEUE_SET CTLV_OP_ID(CTLV_FAMILY_ID, 7)
#define CTLV_OP_OP_CHANGED CTLV_OP_ID(CTLV_FAMILY_ID, 8)
#define CTLV_OP_EVENT_OVERFLOW CTLV_OP_ID(CTLV_FAMILY_ID, 9)
#define CTLV_OP_DEVICE_REMOVED CTLV_OP_ID(CTLV_FAMILY_ID, 10)

#endif /* _UAPI_LINUX_CTLV_GEN_H */
